import { Injectable } from '@angular/core';
import { SelectItem } from 'src/app/shared/models/select-item.model';

@Injectable()
export class CountryService {

    getAllCountries(): Array<SelectItem> {
        let result = new Array<SelectItem>();

        result.push(new SelectItem('AF', 'Afghanistan'));
        result.push(new SelectItem('AL', 'Albania'));
        result.push(new SelectItem('DZ', 'Algeria'));
        result.push(new SelectItem('AO', 'Angola'));
        result.push(new SelectItem('AR', 'Argentina'));
        result.push(new SelectItem('AM', 'Armenia'));
        result.push(new SelectItem('AU', 'Australia'));
        result.push(new SelectItem('AT', 'Austria'));
        result.push(new SelectItem('AZ', 'Azerbaijan'));
        result.push(new SelectItem('BS', 'Bahamas'));
        result.push(new SelectItem('BD', 'Bangladesh'));
        result.push(new SelectItem('BY', 'Belarus'));
        result.push(new SelectItem('BE', 'Belgium'));
        result.push(new SelectItem('BZ', 'Belize'));
        result.push(new SelectItem('BJ', 'Benin'));
        result.push(new SelectItem('BT', 'Bhutan'));
        result.push(new SelectItem('BO', 'Bolivia'));
        result.push(new SelectItem('BA', 'Bosnia and Herzegovina'));
        result.push(new SelectItem('BW', 'Botswana'));
        result.push(new SelectItem('BR', 'Brazil'));
        result.push(new SelectItem('BN', 'Brunei Darussalam'));
        result.push(new SelectItem('BG', 'Bulgaria'));
        result.push(new SelectItem('BF', 'Burkina Faso'));
        result.push(new SelectItem('BI', 'Burundi'));
        result.push(new SelectItem('KH', 'Cambodia'));
        result.push(new SelectItem('CM', 'Cameroon'));
        result.push(new SelectItem('CA', 'Canada'));
        result.push(new SelectItem('CI', 'Ivory Coast'));
        result.push(new SelectItem('CF', 'Central African Republic'));
        result.push(new SelectItem('TD', 'Chad'));
        result.push(new SelectItem('CL', 'Chile'));
        result.push(new SelectItem('CN', 'China'));
        result.push(new SelectItem('CO', 'Colombia'));
        result.push(new SelectItem('CG', 'Congo'));
        result.push(new SelectItem('CD', 'Democratic Republic of Congo'));
        result.push(new SelectItem('CR', 'Costa Rica'));
        result.push(new SelectItem('HR', 'Croatia'));
        result.push(new SelectItem('CU', 'Cuba'));
        result.push(new SelectItem('CY', 'Cyprus'));
        result.push(new SelectItem('CZ', 'Czechia'));
        result.push(new SelectItem('DK', 'Denmark'));
        result.push(new SelectItem('DP', 'Diamond Princess'));
        result.push(new SelectItem('DJ', 'Djibouti'));
        result.push(new SelectItem('DO', 'Dominican Republic'));
        result.push(new SelectItem('CD', 'DR Congo'));
        result.push(new SelectItem('EC', 'Ecuador'));
        result.push(new SelectItem('EG', 'Egypt'));
        result.push(new SelectItem('SV', 'El Salvador'));
        result.push(new SelectItem('GQ', 'Equatorial Guinea'));
        result.push(new SelectItem('ER', 'Eritrea'));
        result.push(new SelectItem('EE', 'Estonia'));
        result.push(new SelectItem('ET', 'Ethiopia'));
        result.push(new SelectItem('FK', 'Falkland Islands'));
        result.push(new SelectItem('FJ', 'Fiji'));
        result.push(new SelectItem('FI', 'Finland'));
        result.push(new SelectItem('FR', 'France'));
        result.push(new SelectItem('GF', 'French Guiana'));
        result.push(new SelectItem('TF', 'French Southern Territories'));
        result.push(new SelectItem('GA', 'Gabon'));
        result.push(new SelectItem('GM', 'Gambia'));
        result.push(new SelectItem('GE', 'Georgia'));
        result.push(new SelectItem('DE', 'Germany'));
        result.push(new SelectItem('GH', 'Ghana'));
        result.push(new SelectItem('GR', 'Greece'));
        result.push(new SelectItem('GL', 'Greenland'));
        result.push(new SelectItem('GT', 'Guatemala'));
        result.push(new SelectItem('GN', 'Guinea'));
        result.push(new SelectItem('GW', 'Guinea-Bissau'));
        result.push(new SelectItem('GY', 'Guyana'));
        result.push(new SelectItem('HT', 'Haiti'));
        result.push(new SelectItem('HN', 'Honduras'));
        result.push(new SelectItem('HK', 'Hong Kong'));
        result.push(new SelectItem('HU', 'Hungary'));
        result.push(new SelectItem('IS', 'Iceland'));
        result.push(new SelectItem('IN', 'India'));
        result.push(new SelectItem('ID', 'Indonesia'));
        result.push(new SelectItem('IR', 'Iran'));
        result.push(new SelectItem('IQ', 'Iraq'));
        result.push(new SelectItem('IE', 'Ireland'));
        result.push(new SelectItem('IL', 'Israel'));
        result.push(new SelectItem('IT', 'Italy'));
        result.push(new SelectItem('JM', 'Jamaica'));
        result.push(new SelectItem('JP', 'Japan'));
        result.push(new SelectItem('JO', 'Jordan'));
        result.push(new SelectItem('KZ', 'Kazakhstan'));
        result.push(new SelectItem('KE', 'Kenya'));
        result.push(new SelectItem('KP', 'Korea'));
        result.push(new SelectItem('XK', 'Kosovo'));
        result.push(new SelectItem('KW', 'Kuwait'));
        result.push(new SelectItem('KG', 'Kyrgyzstan'));
        result.push(new SelectItem('LA', 'Lao'));
        result.push(new SelectItem('LV', 'Latvia'));
        result.push(new SelectItem('LB', 'Lebanon'));
        result.push(new SelectItem('LS', 'Lesotho'));
        result.push(new SelectItem('LR', 'Liberia'));
        result.push(new SelectItem('LY', 'Libya'));
        result.push(new SelectItem('LT', 'Lithuania'));
        result.push(new SelectItem('LU', 'Luxembourg'));
        result.push(new SelectItem('MK', 'Macedonia'));
        result.push(new SelectItem('MG', 'Madagascar'));
        result.push(new SelectItem('MW', 'Malawi'));
        result.push(new SelectItem('MY', 'Malaysia'));
        result.push(new SelectItem('ML', 'Mali'));
        result.push(new SelectItem('MR', 'Mauritania'));
        result.push(new SelectItem('MX', 'Mexico'));
        result.push(new SelectItem('MD', 'Moldova'));
        result.push(new SelectItem('MN', 'Mongolia'));
        result.push(new SelectItem('ME', 'Montenegro'));
        result.push(new SelectItem('MA', 'Morocco'));
        result.push(new SelectItem('MZ', 'Mozambique'));
        result.push(new SelectItem('MM', 'Myanmar'));
        result.push(new SelectItem('NA', 'Namibia'));
        result.push(new SelectItem('NP', 'Nepal'));
        result.push(new SelectItem('NL', 'Netherlands'));
        result.push(new SelectItem('NC', 'New Caledonia'));
        result.push(new SelectItem('NZ', 'New Zealand'));
        result.push(new SelectItem('NI', 'Nicaragua'));
        result.push(new SelectItem('NE', 'Niger'));
        result.push(new SelectItem('NG', 'Nigeria'));
        result.push(new SelectItem('KP', 'North Korea'));
        result.push(new SelectItem('NO', 'Norway'));
        result.push(new SelectItem('OM', 'Oman'));
        result.push(new SelectItem('PK', 'Pakistan'));
        result.push(new SelectItem('PS', 'Palestine'));
        result.push(new SelectItem('PA', 'Panama'));
        result.push(new SelectItem('PG', 'Papua New Guinea'));
        result.push(new SelectItem('PY', 'Paraguay'));
        result.push(new SelectItem('PE', 'Peru'));
        result.push(new SelectItem('PH', 'Philippines'));
        result.push(new SelectItem('PL', 'Poland'));
        result.push(new SelectItem('PT', 'Portugal'));
        result.push(new SelectItem('PR', 'Puerto Rico'));
        result.push(new SelectItem('QA', 'Qatar'));
        result.push(new SelectItem('XK', 'Republic of Kosovo'));
        result.push(new SelectItem('RO', 'Romania'));
        result.push(new SelectItem('RU', 'Russia'));
        result.push(new SelectItem('RW', 'Rwanda'));
        result.push(new SelectItem('SA', 'Saudi Arabia'));
        result.push(new SelectItem('SN', 'Senegal'));
        result.push(new SelectItem('RS', 'Serbia'));
        result.push(new SelectItem('SL', 'Sierra Leone'));
        result.push(new SelectItem('SG', 'Singapore'));
        result.push(new SelectItem('SK', 'Slovakia'));
        result.push(new SelectItem('SI', 'Slovenia'));
        result.push(new SelectItem('SB', 'Solomon Islands'));
        result.push(new SelectItem('SO', 'Somalia'));
        result.push(new SelectItem('ZA', 'South Africa'));
        result.push(new SelectItem('KR', 'South Korea'));
        result.push(new SelectItem('SS', 'South Sudan'));
        result.push(new SelectItem('ES', 'Spain'));
        result.push(new SelectItem('LK', 'Sri Lanka'));
        result.push(new SelectItem('SD', 'Sudan'));
        result.push(new SelectItem('SR', 'Suriname'));
        result.push(new SelectItem('SJ', 'Svalbard and Jan Mayen'));
        result.push(new SelectItem('SZ', 'Swaziland'));
        result.push(new SelectItem('SE', 'Sweden'));
        result.push(new SelectItem('CH', 'Switzerland'));
        result.push(new SelectItem('SY', 'Syrian Arab Republic'));
        result.push(new SelectItem('TW', 'Taiwan'));
        result.push(new SelectItem('TJ', 'Tajikistan'));
        result.push(new SelectItem('TZ', 'Tanzania'));
        result.push(new SelectItem('TH', 'Thailand'));
        result.push(new SelectItem('TL', 'Timor-Leste'));
        result.push(new SelectItem('TG', 'Togo'));
        result.push(new SelectItem('TT', 'Trinidad and Tobago'));
        result.push(new SelectItem('TN', 'Tunisia'));
        result.push(new SelectItem('TR', 'Turkey'));
        result.push(new SelectItem('TM', 'Turkmenistan'));
        result.push(new SelectItem('AE', 'UAE'));
        result.push(new SelectItem('UG', 'Uganda'));
        result.push(new SelectItem('GB', 'United Kingdom'));
        result.push(new SelectItem('UA', 'Ukraine'));
        result.push(new SelectItem('US', 'USA'));
        result.push(new SelectItem('UY', 'Uruguay'));
        result.push(new SelectItem('UZ', 'Uzbekistan'));
        result.push(new SelectItem('VU', 'Vanuatu'));
        result.push(new SelectItem('VE', 'Venezuela'));
        result.push(new SelectItem('VN', 'Vietnam'));
        result.push(new SelectItem('EH', 'Western Sahara'));
        result.push(new SelectItem('YE', 'Yemen'));
        result.push(new SelectItem('ZM', 'Zambia'));
        result.push(new SelectItem('ZW', 'Zimbabwe'));
        
        return result;
    }
}